# Generated by Django 5.0.3 on 2024-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Task title', max_length=20, null=True, verbose_name='Title')),
                ('task', models.TextField(max_length=500, verbose_name='Task')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('In progress', 'In progress'), ('In QA', 'In QA'), ('Ready', 'Ready'), ('Done', 'Done')], default='NEW', max_length=20)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'card',
                'ordering': ['status'],
            },
        ),
    ]
