# Generated by Django 5.0.3 on 2024-04-03 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cardperformer', to=settings.AUTH_USER_MODEL, verbose_name='Performer'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
