# Generated by Django 5.0.3 on 2024-04-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_options_card_card_id_alter_card_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
    ]
